require("user.options")
require("user.lazy")
-- require("user.which-key")
-- require("user.illuminate")
-- require("user.misc")
-- require("user.oil")
-- require('user.wilder')
-- require("user.lualine")
-- require("user.gitsigns")
-- require("user.telescope")
-- require("user.lsp")
-- require("user.trouble")
-- require("user.obsidian")
-- require("user.zenmode")
-- require("user.neogit")
-- require("user.codesnap")
-- require("user.dap")
-- require("user.harpoon")
require("user.keymaps")
--require("user.highlight_yank")
--require("user.toggle_eslint")
--require("user.rotate_windows")
--require("user.resize_windows")
--require("user.vertical_help")
--require("user.edit_text")
-- require("user.kitty_autocmds")
-- require("user.toggle_diagnostics")
